"""Regenerates src/data/eastasianwidth.ts from the CPython the reference itself runs on.

The reference asks `unicodedata.east_asian_width(ch)` and widens on "F" or "W". CPython answers "F" for every
UNASSIGNED code point, so the table below is not the published East Asian Width property: it is what that call
returns, quirk included. Run it under the same Python the reference binary was built with, and diff the result.
"""
import unicodedata
import sys

WIDE = ("F", "W")
BASE = 36

ranges = []
start = None
prev = None
for cp in range(0x110000):
    wide = unicodedata.east_asian_width(chr(cp)) in WIDE
    if wide and start is None:
        start = cp
    elif not wide and start is not None:
        ranges.append((start, prev))
        start = None
    if wide:
        prev = cp
if start is not None:
    ranges.append((start, prev))


def b36(n: int) -> str:
    if n == 0:
        return "0"
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    out = ""
    while n:
        n, r = divmod(n, BASE)
        out = digits[r] + out
    return out


packed = []
at = 0
for lo, hi in ranges:
    packed.append(f"{b36(lo - at)}.{b36(hi - lo)}")
    at = hi

body = ",".join(packed)
lines = [body[i:i + 118] for i in range(0, len(body), 118)]
joined = "\n" + "\n".join(f'  "{line}" +' for line in lines)
joined = joined.rstrip(" +")

print(f"""// GENERATED by scripts/eastasianwidth.py from CPython {sys.version.split()[0]}, unicodedata {unicodedata.unidata_version}.
// Do not edit by hand: rerun the script.
//
// What `unicodedata.east_asian_width(ch) in ("F", "W")` answers, for every code point. It is NOT the published
// property: CPython answers "F" for every UNASSIGNED code point, so those count as WIDE here too, and the reference
// measures them that way. {len(ranges)} ranges, packed as base-36 pairs of (gap from the last range, length).

const PACKED ={joined};

const RADIX = 36;
const PAIR = ".";
const NEXT = ",";

const STARTS: number[] = [];
const ENDS: number[] = [];
{{
  let at = 0;
  for (const pair of PACKED.split(NEXT)) {{
    const [gap, length] = pair.split(PAIR);
    const start = at + Number.parseInt(gap as string, RADIX);
    const end = start + Number.parseInt(length as string, RADIX);
    STARTS.push(start);
    ENDS.push(end);
    at = end;
  }}
}}

/** Whether CPython calls this code point fullwidth or wide. Binary search: the table is sorted and disjoint. */
export function isFullwidthOrWide(cp: number): boolean {{
  let low = 0;
  let high = STARTS.length - 1;
  while (low <= high) {{
    const mid = (low + high) >> 1;
    if (cp < (STARTS[mid] as number)) high = mid - 1;
    else if (cp > (ENDS[mid] as number)) low = mid + 1;
    else return true;
  }}
  return false;
}}""")
