// GENERATED by scripts/eastasianwidth.py from CPython 3.11.9, unicodedata 14.0.0.
// Do not edit by hand: rerun the script.
//
// What `unicodedata.east_asian_width(ch) in ("F", "W")` answers, for every code point. It is NOT the published
// property: CPython answers "F" for every UNASSIGNED code point, so those count as WIDE here too, and the reference
// measures them that way. 710 ranges, packed as base-36 pairs of (gap from the last range, length).

const PACKED =
  "oo.1,7.3,8.0,2.0,l.0,b2.0,13.1,1f.1,4.0,1k.7,s.3,7.a,7j.0,1p.1,2u.d,1o.1,1e.1,g.0,t.1,2.0,c.4,w.0,3.5,6l.0,9.1,3.1,n.0" +
  ",8.0,2.2,5.1,a.1,3.1,5.7,2.3,3.0,6.1,q.1,4.0,7.3,3.1,n.0,8.0,3.0,3.0,3.1,2.0,6.3,3.1,4.2,2.6,5.0,2.6,i.9,4.0,a.0,4.0,n" +
  ".0,8.0,3.0,6.1,b.0,4.0,4.1,2.e,5.1,d.6,8.0,4.0,9.1,3.1,n.0,8.0,3.0,6.1,a.1,3.1,4.6,4.3,3.0,6.1,j.9,3.0,7.2,4.0,5.2,3.0" +
  ",2.0,3.2,3.2,4.2,d.3,6.2,4.0,5.1,2.5,2.d,m.4,e.0,4.0,o.0,h.1,a.0,4.0,5.6,3.0,4.1,2.1,5.1,b.6,n.0,4.0,o.0,b.0,6.1,a.0,4" +
  ".0,5.6,3.5,3.0,5.1,b.0,3.c,e.0,4.0,1g.0,4.0,7.3,h.1,r.0,4.0,j.2,p.0,a.0,2.1,8.2,2.3,7.0,2.0,9.5,b.1,4.b,1n.3,u.10,3.0," +
  "2.0,6.0,p.0,2.0,o.1,6.0,2.0,7.1,b.1,5.v,21.0,11.3,14.0,11.0,g.0,e.10,5j.0,2.4,2.1,1d.2n,6i.0,5.1,8.0,2.0,5.1,16.0,5.1," +
  "y.0,5.1,8.0,2.0,5.1,g.0,1m.0,5.1,1w.1,x.2,r.5,2f.1,7.1,im.2,2i.6,n.8,p.8,l.b,e.0,4.0,3.b,2n.1,b.5,b.5,r.5,2i.6,18.4,1z" +
  ".9,w.0,d.3,d.3,2.2,17.1,6.a,19.3,r.5,c.2,1r.1,1u.0,u.1,c.5,b.5,f.1,w.1c,26.2,1c.0,39.7,1p.2,g.2,1p.6,18.1,c.7,18.4,ev." +
  "1,7.1,13.1,7.1,9.0,2.0,2.0,2.0,w.1,1i.0,g.0,f.1,7.0,k.1,4.0,a.0,2u.0,d.1,s.0,e.2,y.e,y.e,3x.3,az.1,e.1,5b.3,4.0,3.0,1g" +
  ".o,c.k,bi.1,m.1,1f.b,18.0,k.0,e.0,9.1,i.1,6.1,9.0,6.0,m.0,8.1,2.0,5.0,3.0,8.0,5.1,t.0,10.0,2.0,5.2,2.0,1q.2,p.0,f.0,nw" +
  ".1,1g.0,5.0,v.1,x.0,9q.4,1a.0,2.4,2.1,1l.6,3.d,p.8,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,3j.dc,2.ef,9.5f3,1t.h5b,9p.j,55.7,5" +
  "o.4,3.0,2.0,6.n,1o.2,b.5,1l.7,1z.7,d.5,39.a,2.v,27.0,c.3,y.0,1k.8,f.1,b.1,2w.n,t.9,7.1,7.1,7.8,8.0,8.0,1p.3,3j.1,b.8mt" +
  ",o.3,1e.3,6ip.e7,8.b,6.4,r.0,6.0,2.0,3.0,3.0,3i.f,ce.1,1j.6,2.v,x.f,h.1r,6.0,3s.1,2.2o,2n.2,7.1,7.1,7.1,4.a,8.9,6.1,d." +
  "0,r.0,k.0,3.0,g.1,f.x,3g.4,4.3,1a.2,2h.0,e.2,2.1a,1b.3l,u.2,1e.e,t.3,11.8,v.4,18.4,v.0,12.3,f.15,4f.1,b.5,11.3,11.3,15" +
  ".7,1h.a,d.0,g.0,8.0,3.0,c.0,g.0,8.0,3.1u,8o.8,n.9,9.n,7.0,17.0,a.1w,7.1,2.0,19.0,3.2,2.1,o.0,21.7,a.1b,k.0,3.4,y.2,s.4" +
  ",2.1r,1l.3,l.1,1f.0,3.4,9.0,4.0,u.1,4.3,b.6,a.6,1t.v,14.3,d.8,1j.2,u.1,s.4,r.6,5.b,8.27,22.1i,1g.c,1g.6,1b.7,b.85,w.0," +
  "17.0,4.1,3.25,15.7,17.l,r.11,t.j,o.8,27.3,11.8,1x.9,2.1,q.6,b.5,1i.0,j.7,14.8,2p.0,l.a,j.0,19.1s,8.0,2.0,5.0,g.0,c.5,1" +
  "o.4,b.5,5.0,9.1,3.1,n.0,8.0,3.0,6.0,b.1,3.1,4.1,2.5,2.4,8.1,8.2,6.3u,2l.0,6.t,21.7,b.4l,1j.1,13.x,1y.a,b.5,e.i,1n.5,b." +
  "1h,s.1,g.3,o.54,1p.2r,2c.b,9.1,2.1,9.0,3.0,v.0,3.1,d.8,b.1x,9.1,1b.1,c.q,21.7,2c.c,22.7a,a.0,1a.0,f.9,u.2,x.1,n.0,f.20" +
  ",8.0,3.0,19.2,2.0,3.0,a.7,b.5,7.0,3.0,12.0,3.0,7.6,b.8l,q.52,2.e,1f.c,po.2t,34.0,6.a,5h.217,2s.c,ts.0,a.346,g8.6ns,fu." +
  "6,w.0,b.3,2a.0,b.5,v.1,7.9,1z.9,b.0,8.0,m.4,k.j3,2k.2s,24.3,1m.6,i.f33,30.4,e.2,a.6,b.1,9.3mj,1b.1,o.8,39.1n,6v.9,14.1" +
  ",5f.k,1z.49,l.b,2g.8,q.3q,2e.0,20.0,3.1,2.1,3.1,5.0,d.0,2.0,8.0,1u.0,5.1,9.0,8.0,t.0,5.0,6.0,2.2,8.0,9h.1,85.1,jj.e,6." +
  "0,g.un,w.68,8.0,i.1,8.0,3.0,6.5w,1a.2,f.1,b.3,3.8v,w.g,1n.4,2.yn,8.0,5.0,3.0,g.0,5i.1,h.14,25.3,b.3,3.ls,1x.23,1q.5d,5" +
  ".0,s.0,3.0,2.1,2.0,b.0,5.0,2.0,2.5,2.3,2.0,2.0,2.0,4.0,3.0,2.1,2.0,2.0,2.0,2.0,2.0,3.0,2.1,5.0,8.0,5.0,5.0,2.0,b.0,i.4" +
  ",4.0,6.0,i.1f,3.7h,5.0,14.3,2t.b,g.1,g.0,f.1,12.9,3z.0,3.9,k.1j,r.80,d.8,2.1x,2.l,d.16,5.4,d.g,4.0,4.1y,2.0,2.56,3.1q," +
  "e.3,2.n,j.0,r.1,e.0,2f.2c,1d.1x,7.0,4.2,3.a,c.4,5.b,39.b,2i.12,d.3,1l.7,b.5,15.7,v.1,3.25,d.1a,2.9,2.54,2d.b,f.41,44.0" +
  ",1k.10,b.gvly,2.t,2p.3j,6p.1e6n,1ekf.1,1ekf.1";

const RADIX = 36;
const PAIR = ".";
const NEXT = ",";

const STARTS: number[] = [];
const ENDS: number[] = [];
{
  let at = 0;
  for (const pair of PACKED.split(NEXT)) {
    const [gap, length] = pair.split(PAIR);
    const start = at + Number.parseInt(gap as string, RADIX);
    const end = start + Number.parseInt(length as string, RADIX);
    STARTS.push(start);
    ENDS.push(end);
    at = end;
  }
}

/** Whether CPython calls this code point fullwidth or wide. Binary search: the table is sorted and disjoint. */
export function isFullwidthOrWide(cp: number): boolean {
  let low = 0;
  let high = STARTS.length - 1;
  while (low <= high) {
    const mid = (low + high) >> 1;
    if (cp < (STARTS[mid] as number)) high = mid - 1;
    else if (cp > (ENDS[mid] as number)) low = mid + 1;
    else return true;
  }
  return false;
}
